# Site wide configuration

title: Universidade Java
description: Material das aulas, palestras e vídeos sobre desenvolvimento de software.
logo: logo.jpg
teaser: teaser.jpg
locale: pt_BR
url: 

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Rafael Sakurai
  email: rafasakurai@gmail.com
  twitter:
  google:
    ad-client: ca-pub-5328676972596543
    ad-slot: 9892131312
    analytics: UA-21532697-1
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: rafaelsakurai

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
